[package]
name = "binvec"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.4.8", package = "gtk4" }
vtracer = "0.4.0"

# Strip debug symbols in release mode
[profile.release]
strip = "symbols"