[package]
name = "binvec"
version = "0.1.0"
authors = ["Rouven Himmelstein <rouven@himmelstein.info>"]
license = "MIT"
description = "Binarize and vectorize your raster graphics."
readme = "README.md"
homepage = "https://github.com/RouHim/binvec"
repository = "https://github.com/RouHim/binvec"
keywords = ["binarize", "vector"]
edition = "2021"

[dependencies]
gtk = { version = "0.4.1", package = "gtk4" } # As base UI framework
relm4 = "0.4.4" # For gtk4 state management
vtracer = "0.4.0" # For generating the actual vector graphic
visioncortex = "0.6.0" # Helper library for vtracer

# Strip debug symbols in release mode
[profile.release]
strip = "symbols"